/* ============================================
   NEXUSHUB - LANGUAGE SYSTEM
   Full Arabic (RTL) / English (LTR) Support
   ============================================ */

const translations = {
    en: {
        brand: "NexusHub",
        nav_home: "Home",
        nav_blog: "Blog",
        nav_shop: "Shop",
        nav_deals: "Hot Deals",
        nav_join: "Join Free",
        hero_badge: "Live Automation Active",
        hero_title_1: "Build Your",
        hero_title_2: "Digital Empire",
        hero_title_3: "on Autopilot",
        hero_subtitle: "Premium tools, curated deals, and automated growth systems that work while you sleep. Join 10,000+ builders earning real revenue online.",
        hero_cta_primary: "Explore Products",
        hero_cta_secondary: "Start Free",
        stat_users: "Active Users",
        stat_products: "Products",
        stat_rating: "% Satisfaction",
        ad_sponsored: "Sponsored",
        features_tag: "Why Choose Us",
        features_title: "Everything You Need to Scale",
        features_desc: "A complete ecosystem designed for digital entrepreneurs who want results without the complexity.",
        feat_1_title: "Auto-Curated Content",
        feat_1_desc: "Fresh blog posts and resources published daily from verified sources. SEO-optimized and ready to rank.",
        feat_2_title: "Revenue Automation",
        feat_2_desc: "Multiple income streams: AdSense, affiliate commissions, digital product sales, and sponsorships.",
        feat_3_title: "24/7 Growth Engine",
        feat_3_desc: "Automated social posting, SEO updates, and traffic generation running on cloud cron jobs.",
        feat_4_title: "Global Reach",
        feat_4_desc: "Full Arabic and English support with RTL/LTR switching. Reach audiences across MENA and worldwide.",
        blog_tag: "Latest Insights",
        blog_title: "Fresh Content Daily",
        blog_desc: "Auto-curated articles from top sources, optimized for search and engagement.",
        blog_1_title: "10 AI Tools That Will 10x Your Productivity in 2026",
        blog_1_desc: "Discover the cutting-edge artificial intelligence applications transforming how solopreneurs and agencies operate.",
        blog_2_title: "Passive Income Streams: From $0 to $5,000/Month",
        blog_2_desc: "A proven roadmap for building automated revenue channels using digital products and affiliate systems.",
        blog_3_title: "Canva Pro vs. Adobe Express: The Ultimate Comparison",
        blog_3_desc: "Which design platform delivers better ROI for content creators and small business owners?",
        read_more: "Read More",
        shop_tag: "Digital Store",
        shop_title: "Premium Downloads",
        shop_desc: "Instant-access digital products. Keep 100% profit margin with PLR and MRR licenses.",
        badge_bestseller: "Bestseller",
        badge_new: "New",
        btn_view: "View Details",
        prod_1_title: "Ultimate Budget Tracker Excel",
        prod_1_desc: "Automated personal finance spreadsheet with dashboards and yearly projections.",
        prod_2_title: "Social Media Content Calendar 2026",
        prod_2_desc: "365 days of post ideas, captions, and hashtag sets for Instagram, TikTok, and Twitter.",
        prod_3_title: "High-Converting Email Sequence Pack",
        prod_3_desc: "50+ proven email templates for welcome series, launches, and re-engagement campaigns.",
        btn_buy: "Buy Now",
        deals_tag: "Verified Deals",
        deals_title: "Today's Hot Offers",
        deals_desc: "Hand-picked affiliate deals with exclusive discounts. We earn commission— you save money.",
        deal_1_title: "Web Hosting + Free Domain",
        deal_1_feat_1: "Free SSL Certificate",
        deal_1_feat_2: "100GB SSD Storage",
        deal_1_feat_3: "Free Email Accounts",
        deal_2_title: "Canva Pro Annual Plan",
        deal_2_feat_1: "Unlimited Templates",
        deal_2_feat_2: "Brand Kit Access",
        deal_2_feat_3: "Background Remover",
        deal_3_title: "Email Marketing Forever Free",
        deal_3_feat_1: "500 Contacts",
        deal_3_feat_2: "Unlimited Newsletters",
        deal_3_feat_3: "Landing Pages",
        btn_get_deal: "Get Deal →",
        sponsored_slot: "Sponsored Placement",
        sponsored_text: "Your brand here. Contact us for premium sponsored content and banner placements starting at $200/month.",
        btn_advertise: "Advertise With Us",
        news_tag: "Join 10,000+ Builders",
        news_title: "Get Weekly Growth Hacks",
        news_desc: "Free automation scripts, exclusive deals, and revenue strategies delivered every Monday. No spam—unsubscribe anytime.",
        placeholder_email: "your@email.com",
        placeholder_name: "Your Name",
        select_interest: "Select Your Interest...",
        opt_affiliate: "Affiliate Marketing",
        opt_products: "Digital Products",
        opt_automation: "Automation & AI",
        opt_all: "Everything",
        btn_subscribe: "Subscribe Free →",
        form_note: "🔒 We respect your privacy. No spam, ever.",
        social_proof: "Joined this week by 247 entrepreneurs",
        member_tag: "Premium Access",
        member_title: "NexusHub Pro",
        member_desc: "Unlock exclusive tools, early access to deals, and direct mentorship.",
        plan_free: "Starter",
        plan_pro: "Pro Builder",
        plan_agency: "Agency",
        period_month: "/mo",
        free_feat_1: "Weekly newsletter",
        free_feat_2: "Basic deal alerts",
        free_feat_3: "Community access",
        btn_join_free: "Join Free",
        badge_popular: "Most Popular",
        pro_feat_1: "Everything in Starter",
        pro_feat_2: "Monthly PLR product pack",
        pro_feat_3: "Automation scripts library",
        pro_feat_4: "Priority deal alerts",
        pro_feat_5: "Direct email support",
        btn_upgrade: "Upgrade Now",
        agency_feat_1: "Everything in Pro",
        agency_feat_2: "White-label products",
        agency_feat_3: "Reseller rights",
        agency_feat_4: "1-on-1 strategy call",
        btn_contact: "Contact Us",
        footer_desc: "Automated digital growth platform. Built for entrepreneurs who want results.",
        footer_links_1: "Platform",
        footer_feat: "Features",
        footer_shop: "Digital Store",
        footer_deals: "Hot Deals",
        footer_pricing: "Pricing",
        footer_links_2: "Resources",
        footer_blog: "Blog",
        footer_guides: "Guides",
        footer_tools: "Free Tools",
        footer_aff: "Affiliate Program",
        footer_links_3: "Legal",
        footer_privacy: "Privacy Policy",
        footer_terms: "Terms of Service",
        footer_cookies: "Cookie Policy",
        footer_contact: "Contact",
        footer_copy: "© 2026 NexusHub. All rights reserved. Built with automation.",
        footer_aff_disclaimer: "This site contains affiliate links. We earn commission on qualifying purchases at no extra cost to you."
    },
    ar: {
        brand: "نكسس هاب",
        nav_home: "الرئيسية",
        nav_blog: "المدونة",
        nav_shop: "المتجر",
        nav_deals: "عروض حصرية",
        nav_join: "انضم مجاناً",
        hero_badge: "الأتمتة نشطة الآن",
        hero_title_1: "ابنِ",
        hero_title_2: "إمبراطوريتك الرقمية",
        hero_title_3: "على الطيار الآلي",
        hero_subtitle: "أدوات متميزة، صفقات مختارة، وأنظمة نمو آلية تعمل أثناء نومك. انضم إلى أكثر من 10,000 باني يحققون دخلاً حقيقياً عبر الإنترنت.",
        hero_cta_primary: "استكشف المنتجات",
        hero_cta_secondary: "ابدأ مجاناً",
        stat_users: "مستخدم نشط",
        stat_products: "منتج",
        stat_rating: "% رضا",
        ad_sponsored: "إعلان ممول",
        features_tag: "لماذا تختارنا",
        features_title: "كل ما تحتاجه للنمو",
        features_desc: "نظام بيئي متكامل مصمم لرواد الأعمال الرقميين الذين يريدون النتائج دون التعقيد.",
        feat_1_title: "محتوى منسق تلقائياً",
        feat_1_desc: "مقالات وموارد جديدة تنشر يومياً من مصادر موثوقة. محسّنة لمحركات البحث وجاهزة للتصنيف.",
        feat_2_title: "أتمتة الإيرادات",
        feat_2_desc: "تدفقات دخل متعددة: أدسنس، عمولات التسويق بالعمولة، مبيعات المنتجات الرقمية، والرعايات.",
        feat_3_title: "محرك النمو 24/7",
        feat_3_desc: "نشر اجتماعي آلي، تحديثات SEO، وتوليد حركة مرور يعمل على وظائف Cron السحابية.",
        feat_4_title: "الوصول العالمي",
        feat_4_desc: "دعم كامل للعربية والإنجليزية مع التبديل بين RTL/LTR. الوصول إلى الجماهير عبر الشرق الأوسط و العالم.",
        blog_tag: "أحدث الرؤى",
        blog_title: "محتوى جديد يومياً",
        blog_desc: "مقالات منسقة تلقائياً من أفضل المصادر، محسّنة للبحث والتفاعل.",
        blog_1_title: "10 أدوات ذكاء اصطناعي ستضاعف إنتاجيتك 10 مرات في 2026",
        blog_1_desc: "اكتشف تطبيقات الذكاء الاصطناعي المتطورة التي تحول طريقة عمل رواد الأعمال الفرديين والوكالات.",
        blog_2_title: "مصادر الدخل السلبي: من 0 إلى 5,000 دولار شهرياً",
        blog_2_desc: "خارطة طريق مجربة لبناء قنوات إيرادات آلية باستخدام المنتجات الرقمية وأنظمة التسويق بالعمولة.",
        blog_3_title: "Canva Pro مقابل Adobe Express: المقارنة الشاملة",
        blog_3_desc: "أي منصة تصميم تقدم عائد استثمار أفضل لمنشئي المحتوى وأصحاب الأعمال الصغيرة؟",
        read_more: "اقرأ المزيد",
        shop_tag: "المتجر الرقمي",
        shop_title: "تنزيلات متميزة",
        shop_desc: "منتجات رقمية فورية الوصول. احتفظ بـ 100٪ هامش الربح مع تراخيص PLR و MRR.",
        badge_bestseller: "الأكثر مبيعاً",
        badge_new: "جديد",
        btn_view: "عرض التفاصيل",
        prod_1_title: "تتبع الميزانية النهائي لإكسيل",
        prod_1_desc: "جدول مالي شخصي آلي مع لوحات معلومات وتوقعات سنوية.",
        prod_2_title: "تقويم محتوى التواصل الاجتماعي 2026",
        prod_2_desc: "365 يوماً من أفكار المنشورات والتعليقات ومجموعات الهاشتاغ لإنستغرام وتيك توك وتويتر.",
        prod_3_title: "حزمة تسلسلات البريد الإلكتروني عالية التحويل",
        prod_3_desc: "أكثر من 50 قالب بريد إلكتروني مجرب لسلسلة الترحيب والإطلاق وحملات إعادة التفاعل.",
        btn_buy: "اشتري الآن",
        deals_tag: "صفقات موثقة",
        deals_title: "أفضل العروض اليوم",
        deals_desc: "صفقات تسويق بالعمولة مختارة يدوياً مع خصومات حصرية. نحن نكسب عمولة— وأنت توفر المال.",
        deal_1_title: "استضافة ويب + نطاق مجاني",
        deal_1_feat_1: "شهادة SSL مجانية",
        deal_1_feat_2: "100 جيجا تخزين SSD",
        deal_1_feat_3: "حسابات بريد إلكتروني مجانية",
        deal_2_title: "خطة Canva Pro السنوية",
        deal_2_feat_1: "قوالب غير محدودة",
        deal_2_feat_2: "الوصول إلى مجموعة العلامة التجارية",
        deal_2_feat_3: "أداة إزالة الخلفية",
        deal_3_title: "التسويق بالبريد الإلكتروني مجاناً للأبد",
        deal_3_feat_1: "500 جهة اتصال",
        deal_3_feat_2: "رسائل إخبارية غير محدودة",
        deal_3_feat_3: "صفحات الهبوط",
        btn_get_deal: "احصل على العرض →",
        sponsored_slot: "مساحة إعلانية ممولة",
        sponsored_text: "علامتك التجارية هنا. تواصل معنا للمحتوى الرعائي المتميز ومساحات الإعلانات البانر ابتداءً من 200 دولار شهرياً.",
        btn_advertise: "أعلن معنا",
        news_tag: "انضم إلى أكثر من 10,000 باني",
        news_title: "احصل على حيل النمو الأسبوعية",
        news_desc: "سكربتات أتمتة مجانية، صفقات حصرية، واستراتيجيات إيرادات تُرسل كل يوم اثنين. لا رسائل مزعجة— يمكنك إلغاء الاشتراك في أي وقت.",
        placeholder_email: "بريدك@الإلكتروني.com",
        placeholder_name: "اسمك",
        select_interest: "اختر اهتمامك...",
        opt_affiliate: "التسويق بالعمولة",
        opt_products: "المنتجات الرقمية",
        opt_automation: "الأتمتة والذكاء الاصطناعي",
        opt_all: "كل شيء",
        btn_subscribe: "اشترك مجاناً →",
        form_note: "🔒 نحترم خصوصيتك. لا رسائل مزعجة، أبداً.",
        social_proof: "انضم هذا الأسبوع 247 رائد أعمال",
        member_tag: "وصول متميز",
        member_title: "نكسس هاب برو",
        member_desc: "افتح أدوات حصرية، وصول مبكر للصفقات، وإرشاد مباشر.",
        plan_free: "البداية",
        plan_pro: "برو بيلدر",
        plan_agency: "الوكالة",
        period_month: "/شهر",
        free_feat_1: "النشرة الإخبارية الأسبوعية",
        free_feat_2: "تنبيهات الصفقات الأساسية",
        free_feat_3: "الوصول إلى المجتمع",
        btn_join_free: "انضم مجاناً",
        badge_popular: "الأكثر شعبية",
        pro_feat_1: "كل شيء في البداية",
        pro_feat_2: "حزمة منتجات PLR شهرية",
        pro_feat_3: "مكتبة سكربتات الأتمتة",
        pro_feat_4: "تنبيهات صفقات ذات أولوية",
        pro_feat_5: "دعم بريد إلكتروني مباشر",
        btn_upgrade: "ترقية الآن",
        agency_feat_1: "كل شيء في برو",
        agency_feat_2: "منتجات ذات علامة بيضاء",
        agency_feat_3: "حقوق إعادة البيع",
        agency_feat_4: "مكالمة استراتيجية فردية",
        btn_contact: "تواصل معنا",
        footer_desc: "منصة نمو رقمي آلي. مبنية لرواد الأعمال الذين يريدون النتائج.",
        footer_links_1: "المنصة",
        footer_feat: "المميزات",
        footer_shop: "المتجر الرقمي",
        footer_deals: "العروض الحصرية",
        footer_pricing: "الأسعار",
        footer_links_2: "الموارد",
        footer_blog: "المدونة",
        footer_guides: "الأدلة",
        footer_tools: "أدوات مجانية",
        footer_aff: "برنامج التسويق بالعمولة",
        footer_links_3: "قانوني",
        footer_privacy: "سياسة الخصوصية",
        footer_terms: "شروط الخدمة",
        footer_cookies: "سياسة الكوكيز",
        footer_contact: "تواصل معنا",
        footer_copy: "© 2026 نكسس هاب. جميع الحقوق محفوظة. مبني بالأتمتة.",
        footer_aff_disclaimer: "يحتوي هذا الموقع على روابط تسويق بالعمولة. نكسب عمولة على المشتريات المؤهلة دون أي تكلفة إضافية عليك."
    }
};

// Export for main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = translations;
}
